name: gamezone
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.1.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#040009"
  adaptive_icon_foreground: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/font/poppinsregular.ttf
        - asset: assets/font/poppinslight.ttf
        - asset: assets/font/poppinsmedium.ttf
        - asset: assets/font/poppinsbold.ttf
    - family: DMSans
      fonts:
        - asset: assets/font/dmsanslight.ttf
        - asset: assets/font/dmsansregular.ttf
        - asset: assets/font/dmsansmedium.ttf
        - asset: assets/font/dmsansbold.ttf